import {useEffect,useRef,useState} from 'react';
import {api} from './api';
import {Field,JobMonitor,Panel,PathField} from './components';
import type {PageProps} from './pages';
import {LegacyDefects} from './legacy-defects';
import {Comparison,MaskEditor,type MaskHandle} from './datagen-editor';
type Item={id:string;name:string;class_name:string;archived:boolean};
type DataImage={id:string;item_id:string;source:string;role:string;split:string;group:string;mask:string};
type Checkpoint={id:string;step:number;epoch:number;train_loss:number|null;val_loss:number|null;val_defect_loss:number|null;val_background_loss:number|null};
type Model={id:string;item_id:string;status:string;best_val_loss:string|null;best_quality:string|null;last:string|null;checkpoints:Checkpoint[]};
type Sample={id:string;item_id:string;model_id:string;review:{status:string;mask:string;reason:string};seed:number;generation_sec:number};
type Store={settings?:Record<string,any>;items:Item[];images:DataImage[];datasets:{id:string;item_id:string;images:DataImage[]}[];models:Model[];samples:Sample[]};
const imageURL=(collection:string,id:string,kind:string)=>`/api/datagen/image/${collection}/${id}/${kind}`;
const metric=(n:number|null|undefined)=>n==null?'미측정':n.toFixed(6);
function LossGraph({rows}:{rows:Checkpoint[]}){
 const values=rows.flatMap(r=>[r.train_loss,r.val_loss]).filter((x):x is number=>x!==null&&Number.isFinite(x));
 if(!values.length)return <p className="dg-empty">학습 후 실제 Train Loss와 Val Loss를 표시합니다.</p>;
 const max=Math.max(...values,1e-8),steps=Math.max(...rows.map(r=>r.step),1);
 return <figure className="dg-loss"><svg viewBox="0 0 600 150" role="img" aria-label="학습 및 검증 손실"><path d="M30 10V130H590" fill="none" stroke="#aab4c5"/>{(['train_loss','val_loss'] as const).map((key,i)=><g key={key} fill={i?'#1428a0':'#7f8da3'}>{rows.filter(r=>r[key]!==null).map(r=><circle key={r.id} cx={30+r.step/steps*550} cy={130-r[key]!/max*110} r="3"><title>{key}: {r[key]} / step {r.step}</title></circle>)}</g>)}</svg><figcaption>회색: Train Loss / 파랑: Val Loss. 실제 체크포인트 측정값입니다.</figcaption></figure>;
}
export function Defects(props:PageProps){
 const {state,run,act,busy}=props,project=state.project;
 const [data,setData]=useState<Store|null>(null),[tab,setTab]=useState(0),[legacy,setLegacy]=useState(false);
 const [itemId,setItemId]=useState(''),[imageId,setImageId]=useState(''),[modelId,setModelId]=useState(''),[sampleId,setSampleId]=useState('');
 const [name,setName]=useState(''),[className,setClassName]=useState(''),[folder,setFolder]=useState(''),[masks,setMasks]=useState('');
 const [role,setRole]=useState('defect'),[split,setSplit]=useState('train'),[group,setGroup]=useState('');
 const [base,setBase]=useState(''),[prompt,setPrompt]=useState(''),[steps,setSteps]=useState(500),[interval,setIntervalValue]=useState(50);
 const [resolution,setResolution]=useState(512),[rank,setRank]=useState(8),[lr,setLr]=useState(.0001),[precision,setPrecision]=useState('fp32');
 const [patience,setPatience]=useState(0),[delta,setDelta]=useState(0),[checkpoint,setCheckpoint]=useState('');
 const [normalId,setNormalId]=useState(''),[count,setCount]=useState(10),[seed,setSeed]=useState(42),[allowed,setAllowed]=useState('');
 const [filter,setFilter]=useState('pending'),[reason,setReason]=useState(''),[output,setOutput]=useState('');
 const [monitor,setMonitor]=useState<string|null>(null),[error,setError]=useState('');
 const annotation=useRef<MaskHandle>(null),generation=useRef<MaskHandle>(null),review=useRef<MaskHandle>(null);
 const scope=useRef(project?.filepath);scope.current=project?.filepath;
 const refresh=async()=>{const path=project?.filepath;const value=await api<Store>('/datagen');if(scope.current===path)setData(value);};
 useEffect(()=>{let live=true;setData(null);setItemId('');setImageId('');setModelId('');setSampleId('');setNormalId('');setMonitor(null);setAllowed('');setCheckpoint('');setError('');setOutput(project?`${project.project_dir}/synthetic`:'');if(project)api<Store>('/datagen').then(value=>{if(live){setData(value);const saved=value.settings||{};setBase(saved.base_model||'');setPrompt(saved.prompt||'');setSteps(saved.steps||500);setIntervalValue(saved.validate_every||50);setResolution(saved.resolution||512);setRank(saved.rank||8);setLr(saved.learning_rate||.0001);setPrecision(saved.precision||'fp32');setPatience(saved.patience||0);setDelta(saved.min_delta||0);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[project?.filepath]);
 useEffect(()=>{if(!project)return;let live=true;const timer=setInterval(()=>{api<Store>('/datagen').then(value=>{if(live)setData(value);}).catch(e=>{if(live)setError(e.message);});},busy?2000:10000);return()=>{live=false;clearInterval(timer);};},[project?.filepath,busy]);
 const items=data?.items.filter(v=>!v.archived)||[],item=items.find(v=>v.id===itemId);
 const images=data?.images.filter(v=>v.item_id===itemId)||[],defects=images.filter(v=>v.role==='defect'),normals=images.filter(v=>v.role==='normal');
 const current=defects.find(v=>v.id===imageId),models=data?.models.filter(v=>v.item_id===itemId)||[],model=models.find(v=>v.id===modelId);
 const datasets=data?.datasets.filter(v=>v.item_id===itemId)||[],dataset=datasets[datasets.length-1];
 const samples=data?.samples.filter(v=>v.item_id===itemId)||[],sample=samples.find(v=>v.id===sampleId);
 const action=(action:string,values:unknown)=>act(async()=>{await api(`/datagen/${action}`,'POST',{project_path:project!.filepath,values});await refresh();});
 const job=(operation:string,values:unknown)=>act(async()=>{const result=await run(`/jobs/datagen/${operation}`,{project_path:project!.filepath,values});setMonitor(result.id);await refresh();});
 const choose=(id:string)=>{setItemId(id);setImageId('');setModelId('');setSampleId('');setNormalId('');setCheckpoint('');setAllowed('');const selected=items.find(v=>v.id===id);setName(selected?.name||'');setClassName(selected?.class_name||'');};
 const modelSelect=<Field label="학습 모델"><select value={modelId} onChange={e=>{setModelId(e.target.value);setCheckpoint('');}}><option value="">모델 선택</option>{models.map(v=><option key={v.id} value={v.id}>{v.id.slice(0,8)} / {v.status} / {v.best_quality?'품질 검수됨':'품질 미검증'}</option>)}</select></Field>;
 if(!project)return <Panel title="Data Gen"><p>프로젝트를 먼저 여세요.</p></Panel>;
 return <><Panel title="Data Gen"><div className="dg-heading"><p>실제 불량을 학습하고 정상 제품의 지정 영역에 생성합니다.</p><button onClick={()=>setLegacy(!legacy)}>{legacy?'AI Data Gen으로 돌아가기':'기존 규칙 증강 도구'}</button></div>
 {!legacy&&<><div className="dg-tabs" role="tablist">{['1 불량 데이터','2 불량 학습','3 생성','4 검수'].map((label,index)=><button role="tab" aria-selected={tab===index} key={label} onClick={()=>setTab(index)}>{label}</button>)}</div><div className="toolbar"><Field label="학습 항목"><select disabled={busy} value={itemId} onChange={e=>choose(e.target.value)}><option value="">사용자 정의 항목 선택</option>{items.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><span className="muted">실제 불량 {defects.length}장 / 정상 {normals.length}장 / 마스크 완료 {defects.filter(v=>v.mask).length}장</span></div>{error&&<p role="alert">{error}</p>}
 {tab===0&&<><fieldset disabled={busy}><div className="form-grid"><Field label="학습 항목명"><input value={name} onChange={e=>setName(e.target.value)} placeholder="학습할 외관을 직접 입력"/></Field><Field label="검사 클래스 연결"><select value={className} onChange={e=>setClassName(e.target.value)}><option value="">미연결: 생성 검수만 가능</option>{project.data.class_names.map(v=><option key={v}>{v}</option>)}</select></Field></div><div className="toolbar"><button className="primary" disabled={!name.trim()} onClick={()=>action('item',{name,class_name:className})}>학습 항목 추가</button><button disabled={!item} onClick={()=>action('item',{item_id:itemId,name,class_name:className})}>이름과 클래스 저장</button><button disabled={!item} onClick={()=>action('item',{item_id:itemId,name:item!.name,class_name:item!.class_name,archived:true})}>항목 보관</button></div></fieldset>
 {item&&<><fieldset disabled={busy}><details open={!images.length}><summary>실제 이미지 가져오기</summary><div className="form-grid"><PathField label="이미지 폴더" directory value={folder} onChange={setFolder} home={state.home}/><PathField label="마스크 폴더 (선택)" directory value={masks} onChange={setMasks} home={state.home}/><Field label="데이터 종류"><select value={role} onChange={e=>setRole(e.target.value)}><option value="defect">실제 불량</option><option value="normal">실제 정상</option></select></Field><Field label="생성 모델 데이터 분할"><select value={split} onChange={e=>setSplit(e.target.value)}><option value="train">Train</option><option value="val">Val</option></select></Field><Field label="개체 / 생산 로트 그룹"><input value={group} onChange={e=>setGroup(e.target.value)} placeholder="같은 원본과 로트는 같은 그룹"/></Field></div><p className="muted">검사 프로젝트의 평가 폴더는 가져올 수 없습니다. 마스크는 이미지와 같은 상대 경로의 PNG입니다.</p><button disabled={!folder||!group.trim()} onClick={()=>action('import',{item_id:itemId,folder,masks,role,split,group})}>실제 데이터 가져오기</button></details></fieldset><div className="dg-workspace"><aside className="dg-thumbnails">{defects.map(v=><button key={v.id} className={imageId===v.id?'active':''} onClick={()=>setImageId(v.id)}><img alt="실제 불량" src={imageURL('images',v.id,'image')}/><span>{v.split} / {v.group}<br/>{v.mask?'마스크 저장됨':'마스크 필요'}</span></button>)}</aside><div>{current?<><MaskEditor key={current.id+current.mask} ref={annotation} image={imageURL('images',current.id,'image')} initialMask={current.mask?imageURL('images',current.id,'mask')+`?v=${current.mask}`:undefined}/><button disabled={busy} className="primary" onClick={()=>action('mask',{image_id:current.id,mask:{png:annotation.current!.png()}})}>불량 마스크 검수 저장</button></>:<p className="dg-empty">실제 불량 이미지를 선택하고 학습할 영역을 표시하세요.</p>}</div></div><button disabled={busy||!defects.length} onClick={()=>action('freeze',{item_id:itemId})}>검수 데이터를 새 학습 버전으로 고정</button><span className="muted"> 고정 버전 {datasets.length}개. Train과 Val 모두 필요합니다.</span></>}
 </>}
 {tab===1&&<><p>최소 Val Loss를 자동 Best로 저장합니다. 생성 품질 Best는 검수 후 별도로 선택합니다.</p><fieldset disabled={busy||!item}><div className="form-grid"><PathField label="사전학습 Inpainting 모델 폴더" directory value={base} onChange={setBase} home={state.home}/><Field label="학습할 불량과 표면 설명"><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="제품 표면과 실제 불량 외관"/></Field></div><details><summary>고급 학습 설정</summary><div className="form-grid">{[['학습 Step',steps,setSteps],['검증 주기 Step',interval,setIntervalValue],['해상도',resolution,setResolution],['LoRA rank',rank,setRank],['학습률',lr,setLr],['조기 종료 Patience (0: 사용 안 함)',patience,setPatience],['최소 개선 폭',delta,setDelta]].map(([label,value,setter])=><Field key={String(label)} label={String(label)}><input type="number" value={Number(value)} onChange={e=>(setter as (n:number)=>void)(+e.target.value)}/></Field>)}<Field label="정밀도"><select value={precision} onChange={e=>setPrecision(e.target.value)}><option>fp32</option><option>fp16</option><option>bf16</option></select></Field></div></details><button onClick={()=>action('settings',{values:{base_model:base,prompt,steps,validate_every:interval,resolution,rank,learning_rate:lr,precision,patience,min_delta:delta}})}>학습 설정 저장</button><p>최근 고정 데이터: {dataset?.id.slice(0,8)||'없음'}</p><button className="primary" disabled={!dataset||!base||!prompt} onClick={()=>job('train',{dataset_id:dataset!.id,config:{base_model:base,prompt,steps,validate_every:interval,resolution,rank,learning_rate:lr,precision,patience,min_delta:delta}})}>새 불량 학습</button></fieldset>{modelSelect}
 {model&&<><LossGraph rows={model.checkpoints}/><p>Best Val: {model.best_val_loss?.slice(0,8)||'미선정'} / Best Quality: {model.best_quality?.slice(0,8)||'미선정'} / Last: {model.last?.slice(0,8)||'없음'}</p><div className="dg-table"><table><thead><tr>{['선택','Step / Epoch','Train Loss','Val Loss','불량 영역 Val','배경 Val'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{model.checkpoints.map(c=><tr key={c.id}><td><input aria-label={`체크포인트 ${c.step}`} type="radio" name="checkpoint" checked={checkpoint===c.id} onChange={()=>setCheckpoint(c.id)}/></td><td>{c.step} / {c.epoch.toFixed(2)}</td><td>{metric(c.train_loss)}</td><td>{metric(c.val_loss)}</td><td>{metric(c.val_defect_loss)}</td><td>{metric(c.val_background_loss)}</td></tr>)}</tbody></table></div><div className="toolbar"><button disabled={busy||!model.last} onClick={()=>job('train',{resume_model:model.id})}>Last에서 학습 재개</button><input aria-label="품질 선정 근거" placeholder="고정 생성 샘플의 품질 검수 결과" value={reason} onChange={e=>setReason(e.target.value)}/><button disabled={busy||!checkpoint||!reason.trim()} onClick={()=>action('quality',{model_id:model.id,checkpoint,reason})}>선택 모델을 품질 Best로 지정</button></div></>}
 <p className="muted">CUDA GPU와 Data Gen 전용 환경이 필요합니다. 설치와 실제 GPU 검증 절차: docs/DATA_GEN.md</p></>}
 {tab===2&&<><fieldset disabled={busy||!item}><div className="form-grid">{modelSelect}<Field label="실제 정상 이미지"><select value={normalId} onChange={e=>{setNormalId(e.target.value);setAllowed('');}}><option value="">정상 이미지 선택</option>{normals.map(v=><option key={v.id} value={v.id}>{v.source.split(/[\\/]/).pop()} / {v.group}</option>)}</select></Field></div></fieldset>{normalId&&<MaskEditor key={normalId} ref={generation} image={imageURL('images',normalId,'image')} label="생성 요청 영역"/>}<fieldset disabled={busy}><details><summary>생성 수와 고급 설정</summary><div className="form-grid"><Field label="대량 생성 수"><input type="number" min={1} max={100} value={count} onChange={e=>setCount(+e.target.value)}/></Field><Field label="시드"><input type="number" value={seed} onChange={e=>setSeed(+e.target.value)}/></Field><PathField label="허용 영역 마스크 (비우면 요청 영역만 허용)" value={allowed} onChange={setAllowed} home={state.home}/></div></details><div className="toolbar">{[1,count].map((n,i)=><button key={i} className={i?'':'primary'} disabled={!normalId||!model?.last} onClick={()=>job('generate',{model_id:model!.id,image_id:normalId,requested:{png:generation.current!.png()},allowed:allowed||undefined,count:n,seed,...(checkpoint?{checkpoint}:{})})}>{i?'대량 생성':'샘플 생성'}</button>)}</div></fieldset><p className="muted">생성 후 검수 탭에서 저장된 결과를 확인하세요. 규칙 증강으로 대체 실행하지 않습니다.</p></>}
 {tab===3&&<><div className="toolbar"><Field label="검수 상태"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">미검수</option><option value="approved">승인</option><option value="rejected">제외</option><option value="all">전체</option></select></Field><span>승인 {samples.filter(v=>v.review.status==='approved').length} / 제외 {samples.filter(v=>v.review.status==='rejected').length} / 전체 {samples.length}</span></div><div className="dg-workspace"><aside className="dg-thumbnails">{samples.filter(v=>filter==='all'||v.review.status===filter).map(v=><button key={v.id} onClick={()=>{setSampleId(v.id);setReason(v.review.reason);}} className={sampleId===v.id?'active':''}><img alt="생성 후보" src={imageURL('samples',v.id,'image')}/><span>{v.id.slice(0,8)} / {v.review.status}</span></button>)}</aside><div>{sample?<><Comparison original={imageURL('samples',sample.id,'original')} result={imageURL('samples',sample.id,'image')}/><details open><summary>불량 정답 라벨 확인과 수정</summary><MaskEditor key={sample.id+sample.review.mask} ref={review} image={imageURL('samples',sample.id,'image')} initialMask={imageURL('samples',sample.id,sample.review.mask?'reviewed':'requested')+`?v=${sample.review.mask}`} label="검수 불량 마스크 (요청 영역은 초안)"/></details><div className="toolbar">{['allowed','requested','changed'].map((kind,i)=><a key={kind} href={imageURL('samples',sample.id,kind)} target="_blank" rel="noreferrer">{['허용 영역','생성 요청','실제 변경'][i]}</a>)}</div><Field label="검수 사유"><input value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="toolbar"><button className="primary" disabled={busy} onClick={()=>action('review',{sample_id:sample.id,status:'approved',mask:{png:review.current!.png()},reason})}>현재 불량 라벨로 승인</button><button disabled={busy} onClick={()=>action('review',{sample_id:sample.id,status:'rejected',reason})}>제외</button><button disabled={busy} onClick={()=>action('review',{sample_id:sample.id,status:'pending',reason})}>미검수로 되돌리기</button></div><p className="muted">시드 {sample.seed} / 생성 {sample.generation_sec.toFixed(2)}초</p></>:<p className="dg-empty">후보를 선택하고 실제 불량 라벨을 검수하세요.</p>}</div></div><Field label="새 학습 버전 저장 폴더"><input value={output} onChange={e=>setOutput(e.target.value)}/></Field><button disabled={busy||!samples.some(v=>v.review.status==='approved')} onClick={()=>action('publish',{sample_ids:samples.filter(v=>v.review.status==='approved').map(v=>v.id),output})}>승인본을 새 학습 버전으로 저장</button><p className="muted">원본을 보존하고 생성 파일과 검수 마스크, 클래스 연결을 포함한 별도 train 버전으로 저장합니다. PatchCore 정상 학습에는 사용하지 않습니다.</p></>}
 </>}</Panel>{legacy&&<LegacyDefects {...props}/>} {monitor&&!legacy&&<JobMonitor id={monitor}/>}</>;
}
